config/routes.rb
Playit::Application.routes.draw do

  get "one/playlist"

  get "one/search"

  get "one/player"

  get "one/lyric"

  get "one/wiki"

  get "players/mini"
  get "players/simple"

  get "list_nodes/clear"
  get "list_nodes/flatten"
  get "list_nodes/move_to"
  get "list_nodes/add_to_playing"
  post "list_nodes/playlist_playable_items"
  resources :list_nodes

  resources :list_heads

  resources :lyrics

  resources :image_files

  resources :audio_files_tags

  get "audio_files/add_to_playing"
  resources :audio_files do
    member do
      get 'add'
    end
  end

  resources :tags

  resources :genres

  resources :songs

  get "albums/lookup"
  get "albums/add_to_playing"
  get "albums/search"

  resources :albums do
    member do
      get 'image'
      get 'add'
    end
  end

  get "artists/search"
  resources :artists do
    resources :albums do
      get 'add'
    end
  end

  resources :file_dirs

  authenticated :user do
    root :to => 'home#index'
    #root :to => 'one#playlist'
  end
  root :to => "home#index"

  get "home/main"
  get "home/search"
  get "home/dosearch"
  post "home/aside"
  get "home/playing_lyrics"
  get "home/playing_wiki"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name, :wikiname

  validates :name, :presence => true, :uniqueness => true

  has_many :audio_files, :dependent => :nullify
  has_many :albums, :through => :audio_files
  has_many :songs, :through => :audio_files
  has_many :genres, :through => :audio_files
  has_many :file_dirs, :through => :audio_files
  has_many :solo_albums, :foreign_key => :album_artist_id, :class_name => 'Album'


  searchable :auto_index => true, :auto_remove => true do
    integer :id

    string :name
    text :name_text, :boost => 0.9 do
      name
    end
    text :name_textp, :stored => true, :boost => 0.5, :as => :name_textp do
      name
    end

    text :album_names, :boost => 0.2  do
      (albums.map(&:name).join(' '))
    end
    # text :song_names, :boost => 0.1  do
    #   (songs.map(&:name).join(' '))
    # end
    
    # text :name, :stored => true, :boost => 9, :as => :name_textp 

    # text :album_names, :boost => 4, :as => :album_names_textp  do
    #   (albums.map{ |a| a.name }.join(' '))
    # end

    # text :song_names, :boost => 3, :as => :song_names_textp  do
    #   (songs.map{ |a| a.name }.join(' '))
    # end

    # integer :album_ids, :multiple => true, :references => Album
    # integer :song_ids, :multiple => true, :references => Song
    # integer :audio_file_ids, :multiple => true, :references => AudioFile
    # integer :genre_ids, :multiple => true, :references => Genre
    # integer :lyric_ids, :multiple => true, :references => Lyric

  end


end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  layout Proc.new { |controller| controller.request.xhr? ? false : 'appfixed' }

  def index
    @q = params[:q]
    per_page = 15
    @q ||= ""
    @search = Sunspot.search(Artist) do |s|
      s.keywords @q
      s.paginate :page => params[:page], :per_page => per_page
    end
    @artists = @search.results
  end


  def search
    @q = params[:q]
    per_page = 15
    if @q
      @search = Sunspot.search(Artist) do |s|
        s.keywords @q
        
        s.paginate :page => params[:page], :per_page => per_page
      end
      @artists = @search.results
    else
      @artists = Artist.page(params[:page]).per(per_page)
    end

    respond_to do |format|
      format.html { render 'index' }
    end



  end


end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_album.html.haml
-# image_file = album.album_image_file
-# image_url = image_file ? image_file.imageurl : "256x256/devices/media-optical-audio_mount.png"
%li.Album.playable{:id => "sr-artist-#{artist.id}-album-#{album.id}"}
  .elem{ 'data-elem_id' => "album-#{album.id}" } 
    .detail-button
      &raquo;
    .elem-image
      = link_to %{<img src="#{albumart_url(album,'small')}" border="0" />}.html_safe, artist_album_add_path(artist.id,album.id), :remote => true, :title => "Add '#{album.name}' to Playing"
    .elem-data
      .name=link_to album.name, album_path(album.id), :class => 'link-name'

app/views/artists/_artist.html.haml
= render :partial => 'artists/aside', :locals => {:artist => artist, :context_rec => context_rec, :lostyle => 'tbl' }

app/views/artists/_aside.html.haml
- case context_rec
- when artist
  %h3.name=artist.name
  .albums
    %table.table.table-striped.table-condensed
      - artist.albums.uniq.each do |album|
        = render :partial => album, :locals => {:context_rec => context_rec, :lostyle => 'tbl' }

app/views/artists/_elem.html.haml
- all_albums = elem.albums.uniq
- all_tracks = all_albums.map{|alb| alb.audio_files.limit_to(elem) }.flatten
.elem.Artist{ 'data-elem_id' => "#{elem.class.to_s.tableize}-#{elem.id}" } 
  .elem-data
    .name
      = link_to elem.name, artist_path(elem.id), :class => 'link-name'
      %span{ :class => 'artist-subname' }
        = '(' + pluralize(all_albums.size,'album') + ')'
      %span{ :class => 'artist-subname' }
        = '(' + pluralize(all_tracks.size,'track') + ')'
  .elem-content
    %ul
      - solo = elem.solo_albums.uniq
      - mult = elem.albums.uniq - solo
      -# mult,solo = elem.albums.uniq.partition{|a| a.artists.uniq.size != 1}
    
      - solo.each do |alb|
        = render :partial => 'artists/album', :object => alb, :locals => { :artist => elem }
      - mult.each do |alb|
        = render :partial => 'artists/album', :object => alb, :locals => { :artist => elem }

app/views/artists/_form.html.haml
= simple_form_for @artist, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :wikiname
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), artists_path, :class => 'btn'

app/views/artists/_hit.html.haml
- all_albums = elem.albums.uniq
-# - all_tracks = all_albums.map{|alb| alb.audio_files.limit_to(elem) }.flatten
- if all_albums.size > 0
  = render :partial => "artists/elem", :object => elem
- else
  = render :partial => "albums/elem", :object => all_albums.first

app/views/artists/_index.html.haml
- content_for :tabs_head do
  %li
    %a{ :href => "#tab-artists", 'data-toggle' => "tab" } Artists

- content_for :tabs_content do
  .tab-pane.active#tab-artists
    = render :partial => 'artists/tab', :locals => { :artists => artists }

app/views/artists/_show.html.haml
- content_for :tabs_head do
  %li
    %a{ :href => "#tab-artist", 'data-toggle' => "tab" } Artist

- content_for :tabs_content do
  .tab-pane.active#tab-artist
    .artist-show
      .row
        .span9
          .page-header
            %h1=artist.name
      .row
        .span9
          = render :partial => "artists/album", :collection => artist.albums.uniq

app/views/artists/_tab.html.haml
- model_class = Artist.new.class
.artist-index
  .row
    .span9
      %h1=t '.title', :default => model_class.model_name.human.pluralize
  .row
    .span9
      %table.table.table-striped.table-condensed
        %thead
          %tr
            %th= model_class.human_attribute_name(:name)
            %th= model_class.human_attribute_name(:wikiname)
            %th=t '.actions', :default => t("helpers.actions")
        %tbody
          - artists.each do |artist|
            %tr
              %td= link_to artist.name, artist_path(artist)
              %td= artist.wikiname
              %td
                = link_to t('.edit', :default => t("helpers.links.edit")), edit_artist_path(artist), :class => 'btn btn-mini'
                = link_to t('.destroy', :default => t("helpers.links.destroy")), artist_path(artist), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'
  .row
    .span9
      = paginate artists


      

app/views/artists/_track.html.haml
%tr
  %td=track.tracknum
  %td=track.song.name
  %td=Time.at(track.length).strftime("%M:%S").sub(/^0/,'')
  

app/views/artists/edit.html.haml
- model_class = @artist.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/artists/index.html.haml
= render :partial => 'home/playing'
= render :partial => 'home/index', :locals => { :q => @q, :search => @search }
= render :partial => 'artists/index', :locals => { :artists => @artists }

app/views/artists/new.html.haml
- model_class = @artist.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/artists/show.html.haml
= render :partial => 'home/playing'
-# = render :partial => 'home/index', :locals => { :q => @q, :search => @search }
= render :partial => 'artists/show', :locals => { :artist => @artist }