config/routes.rb
Playit::Application.routes.draw do

  get "one/playlist"

  get "one/search"

  get "one/player"

  get "one/lyric"

  get "one/wiki"

  get "players/mini"
  get "players/simple"

  get "list_nodes/clear"
  get "list_nodes/flatten"
  get "list_nodes/move_to"
  get "list_nodes/add_to_playing"
  post "list_nodes/playlist_playable_items"
  resources :list_nodes

  resources :list_heads

  resources :lyrics

  resources :image_files

  resources :audio_files_tags

  get "audio_files/add_to_playing"
  resources :audio_files do
    member do
      get 'add'
    end
  end

  resources :tags

  resources :genres

  resources :songs

  get "albums/lookup"
  get "albums/add_to_playing"
  get "albums/search"

  resources :albums do
    member do
      get 'image'
      get 'add'
    end
  end

  get "artists/search"
  resources :artists do
    resources :albums do
      get 'add'
    end
  end

  resources :file_dirs

  authenticated :user do
    root :to => 'home#index'
    #root :to => 'one#playlist'
  end
  root :to => "home#index"

  get "home/main"
  get "home/search"
  get "home/dosearch"
  post "home/aside"
  get "home/playing_lyrics"
  get "home/playing_wiki"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/list_node.rb
class ListNode < ActiveRecord::Base
  has_ancestry :orphan_strategy => :destroy, :cache_depth => true

  acts_as_list :scope => 'ancestry = \'#{ancestry}\''
  scope :ordered, :order => "ancestry_depth,position ASC"

  belongs_to :listable, :polymorphic => true
  attr_accessible :ancestry, :position, :listable, :parent

  scope :my, lambda { |user|
    self.root.joins(:list_heads).where("list_heads.user_id = ?", user.id)
  }



  def create_single_node
    create_nodes([self])
  end

  def create_subtree_nodes
    create_nodes(ListNode.includes(:listable).ordered.subtree_of(self.id).all)
  end

  def create_subtree_nodetree
    NodeTree.subtree_of(self.id)
  end

  def create_nodes(sub_tree)

    nodes = {
      :audio_files => {},
      :albums => {},
      :songs => {},
      :artists => {},
    }
    sub_tree.each do |ln|
      nodes[ln.id] = { 
        :node => ln,
        :children => []
      }
      if ln.parent_id && nodes[ln.parent_id]
        nodes[ln.parent_id][:children] << ln.id
        nodes[ln.listable.class.to_s.tableize.to_sym][ln.listable.id] = ln.listable
      end
    end
    
    af_album_ids = nodes[:audio_files].values.map{|af| af.album_id}
    af_albums = Album.find(af_album_ids)
    nodes[:albums].merge!(Hash[af_albums.map{|s| [s.id,s]}])
    
    af_artist_ids = nodes[:audio_files].values.map{|af| af.artist_id}.uniq
    af_artists = Artist.find(af_artist_ids)
    nodes[:artists] = Hash[af_artists.map{|s| [s.id,s]}]
    
    songs = Song.find(nodes[:audio_files].values.map{|af| af.song_id})
    nodes[:songs] = Hash[songs.map{|s| [s.id,s]}]
    
    file_dirs = FileDir.find(nodes[:audio_files].values.map{|af| af.file_dir_id})
    nodes[:file_dirs] = Hash[file_dirs.map{|s| [s.id,s]}]
    
    nodes
  end





end

app/controllers/list_nodes_controller.rb
class ListNodesController < ApplicationController
  before_filter :authenticate_user!

  layout Proc.new { |controller| controller.request.xhr? ? false : 'appfixed' }

  def move_to
    item_id = record_id(params[:item])
    list_id = record_id(params[:list])
    index = params[:index].to_i
    item = ListNode.find(item_id)

    from_list_id = item.parent_id

    if from_list_id != list_id
      item.remove_from_list
      item.parent_id = list_id
    end
    item.remove_from_list
    item.insert_at( index + 1 )
    
    from_list = ListNode.find(from_list_id)
    
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def move_after
    item_id = record_id(params[:item])
    list_id = record_id(params[:list])
    after_id = record_id(params[:after])

    item = ListNode.find(item_id)
    after = ListNode.find(after_id) if after_id

    if item.parent_id != list_id
      item.remove_from_list
      item.parent_id = list_id
    end
    item.remove_from_list
    item.insert_at( after ? after.position : 1 )

  end

  def flatten
    node = ListNode.find(params[:id].to_i)
    pos = node.position
    child_ids = node.child_ids
    n_holes = child_ids.size - 1
    node.siblings.where(["position > ?",pos]).update_all("position = (position + #{n_holes})")
    to_list_id = node.parent_id
    Rails.logger.info("flatten: pos = #{pos}")

    node.children.each_with_index do |n,i|
      n.parent_id = to_list_id
      n.position = pos + i
      n.save!
      Rails.logger.info("  flatten: i=#{i} insert_at=#{pos+i}")
    end
    node.delete

    respond_to do |format|
      format.js { head :ok }
    end
  end

  def playlist_playable_items
    @active_id = record_id(params[:active_id])
    @list_node = ListHead.my(current_user).playing.all.map(&:list_node).first
    @node_id = @list_node.id
    subtree = ListNode.includes(:listable).ordered.subtree_of(@node_id).all
    @nodetree = NodeTree.new(subtree)

    @playdata = cookies[:playing]
    unless @playdata && @nodetree.playdata_in_tree(@playdata)
      @playdata = @nodetree.create_playdata(@nodetree.first_audio_file_node)
    end

    cookies[:playing] = @playdata ? { :value => @playdata, :expires => Time.now + 3600*24*7} : nil

    respond_to do |format|
      format.html { render :partial => 'list_nodes/playlist_playable_items', :locals => { :nodetree => @nodetree, :node_id => @node_id, :playing_playdata => @playdata } }
    end

  end

  def add_to_playing
    @recs = elem_id_to_records(params[:elem_id])
    list_node = current_user.list_heads.playing.first.list_node

    new_node = @recs[-1].create_list_node_all(list_node)
    @node_id = new_node.id
    subtree = ListNode.includes(:listable).ordered.subtree_of(@node_id).all
    @nodetree = NodeTree.new(subtree)

    respond_to do |format|
      format.js
    end
  end




  def node_sort_key(node,id_to_pos)
    ids = node.ancestry ? node.ancestry.split('/') : []
    poses = ids.map{|ids| id_to_pos[ids.to_i]}
    poses << node.position
    (0..2).map{|i| poses[i] ? poses[i] : 0}
  end
  def index
    # @list_nodes = ListHead.my(current_user).all.map(&:list_node)
    
    # @list_nodes = ListNode.roots.joins(:list_heads).where(["list_heads.user = ?",current_user]).all

    @list_node = ListHead.my(current_user).playing.all.map(&:list_node).first


    @node_id = @list_node.id
    subtree = ListNode.includes(:listable).ordered.subtree_of(@node_id).all
    @nodetree = NodeTree.new(subtree)
  end

  def show
    # @list_node = ListNode.subtree_of(params[:id])
    @list_node = ListNode.find(params[:id])
  end

  # PUT /list_nodes/1
  # PUT /list_nodes/1.json
  def update
    @list_node = ListNode.find(params[:id])

    respond_to do |format|
      if @list_node.update_attributes(params[:list_node])
        format.html { redirect_to @list_node, notice: 'List node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list_node.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /list_nodes/1
  # DELETE /list_nodes/1.json
  def destroy
    @list_node = ListNode.find(params[:id])
    @list_node.destroy
    @node_id = @list_node.id
    respond_to do |format|
      # format.js
      # format.html { redirect_to list_nodes_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/list_nodes_helper.rb
module ListNodesHelper

  def playlist(nodetree, node_id)
    list_node = nodetree.list_node(node_id)
    children = nodetree.children(node_id)
    playdata_class = list_node_playdata_class(list_node)
    playdata_data = list_node_playdata_data(list_node)
  end
    
end
  

app/views/list_nodes/_form.html.haml
= simple_form_for @list_node, :html => { :class => 'form-horizontal' } do |f|
  = f.input :ancestry
  = f.input :ancestry_depth
  = f.input :position
  = f.input :listable_id
  = f.input :listable_type
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), list_nodes_path, :class => 'btn'

app/views/list_nodes/_items.html.haml
- list_node = nodes[node_id][:node]
- children = nodes[node_id][:children]
- af_node_ids = nodes[:audio_files]
.listnode-elem{ :id => "pl-list_node-#{list_node.id}",:class => "#{list_node.listable_type} depth#{list_node.ancestry_depth}" }

  .listnode-header{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth}" }
    = render :partial => "#{list_node.listable_type.tableize}/controls", :locals => {:list_node => list_node}
    .listnode-dbg
      = "#{list_node.ancestry_depth}-#{list_node.position}"
    = render :partial => "#{list_node.listable_type.tableize}/elem", :object => list_node.listable
  - unless children.empty?
    .listnode-content{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth} #{list_node.listable.node_class(list_node)}" }
      - children.each do |nid|
        = render :partial => 'list_nodes/node', :locals => { :nodes => nodes, :node_id => nid }

app/views/list_nodes/_liel.html.haml
- if Array === liel
  %ul.cont
    - liel.each do |el|
      %li.cont-elem
        = render :partial => 'liel', :locals => { :liel => el }

- else
  =liel.inspect

app/views/list_nodes/_node.html.haml
- list_node = nodetree.list_node(node_id)
- children = nodetree.children(node_id)
- playdata_class = list_node_playdata_class(list_node)
- playdata_data = list_node_playdata_data(list_node)
.listnode-elem{ :id => "pl-list_node-#{list_node.id}", :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth} #{playdata_class}", 'data-playdata' => "#{playdata_data}" }

  .listnode-header{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth}" }
    = render :partial => "#{list_node.listable_type.tableize}/controls", :locals => {:list_node => list_node}
    = render :partial => "#{list_node.listable_type.tableize}/elem", :object => nodetree.create_struct(node_id),
    :locals => { :tracks => false, :imgsz => 'large' }
  - unless children.empty? && list_node.listable_type != 'ListHead'  
    - artist_count_class = nodetree.n_child_artists(node_id) == 1 ? 'single-artist' : ''
    .listnode-content{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth} #{artist_count_class}" }
      - children.each do |nid|
        = render :partial => 'list_nodes/node', :locals => { :nodetree => nodetree, :node_id => nid }

app/views/list_nodes/_node2.html.haml
- list_node = nodetree.list_node(node_id)
- children = nodetree.children(node_id)
- playdata_class = list_node_playdata_class(list_node)
- playdata_data = list_node_playdata_data(list_node)
.listnode-elem{ :id => "pl-list_node-#{list_node.id}", :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth} #{playdata_class}", 'data-playdata' => "#{playdata_data}" }

  .listnode-header{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth}" }
    .listnode-controls
      .listnode-ctl
        = link_to '<i class="icon-trash"></i>'.html_safe,list_nodes_clear_path(:id => list_node.id), :method => :get, :title => "Clear playlist contents"
    %h2=list_node.listable.name

  - unless children.empty?
    .listnode-content{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth}" }
      - children.each do |node_id2|

        - list_node2 = nodetree.list_node(node_id2)
        - children2 = nodetree.children(node_id2)
        - playdata_class2 = list_node_playdata_class(list_node2)
        - playdata_data2 = list_node_playdata_data(list_node2)
        .listnode-elem{ :id => "pl-list_node-#{list_node2.id}", :class => "#{list_node2.listable_type} depth#{list_node2.ancestry_depth} #{playdata_class2}", 'data-playdata' => "#{playdata_data2}" }

          .listnode-header{ :class => "#{list_node2.listable_type} depth#{list_node2.ancestry_depth}" }
            .listnode-controls
              .listnode-ctl=link_to '<i class="icon-remove"></i>'.html_safe,list_node_path(list_node2.id), :method => :delete, :title => "Remove From Playlist", :remote => true, :class => "remove-node"
              - if list_node2.listable_type == 'Album'
                .listnode-ctl=link_to '<i class="icon-list-alt"></i>'.html_safe,list_nodes_flatten_path(:id => list_node2.id), :method => :get, :title => "Move Album tracks to playlist", :remote => true, :class => "flatten-node"

            - elem = nodetree.create_struct(node_id2)
            - if list_node2.listable_type == 'AudioFile'
              .elem{ 'data-elem_id' => "audio_file-#{elem.id}" } 
                -# .elem-image=image_tag("note-blue-32.png")
                .elem-data{ "data-sound_id" => "sound_id-audio_file-#{elem.id}", :class => "sound_id-AudioFile"}
                  .duration= Time.at(elem.length).strftime("%M:%S").sub(/^0/,'')
                  .tracknum= elem.tracknum
                  .song= elem.song_name
                  .artist= elem.artist_name
                  .album= elem.album_name
                  .url= link_to "#{elem.song_name} - #{elem.artist_name}",elem.url,:remote => true, :class => 'audiofile-link'
            - elsif list_node2.listable_type == 'Album'
              .elem{ 'data-elem_id' => "album-#{elem.id}" } 
                .elem-image=%{<img src="#{image_album_path(elem.id)}" border="0" />}.html_safe
                .elem-data
                  .name=elem.name
                .elem-content
                  .artists
                    - artists = elem.artists.uniq
                    = artists.first(3).map{|a| a.name }.join(", ").html_safe
                    = (artists.size > 3 ? " &hellip;".html_safe : "")
  
          - unless children2.empty?
            - artist_count_class = nodetree.n_child_artists(node_id2) == 1 ? 'single-artist' : 'multi-artist'
            .listnode-content{ :class => "#{list_node2.listable_type} depth#{list_node2.ancestry_depth} #{artist_count_class}" }
              - children2.each do |node_id3|
                - list_node3 = nodetree.list_node(node_id3)
                - playdata_class3 = list_node_playdata_class(list_node3)
                - playdata_data3 = list_node_playdata_data(list_node3)
                .listnode-elem{ :id => "pl-list_node-#{list_node3.id}", :class => "#{list_node3.listable_type} depth#{list_node3.ancestry_depth} #{playdata_class3}", 'data-playdata' => "#{playdata_data3}" }
                  .listnode-header{ :class => "#{list_node3.listable_type} depth#{list_node3.ancestry_depth}" }
                    .listnode-controls
                      .listnode-ctl=link_to '<i class="icon-remove"></i>'.html_safe,list_node_path(list_node3.id), :method => :delete, :title => "Remove From Playlist", :remote => true, :class => "remove-node"
                    - elem3 = nodetree.create_struct(node_id3)
                    .elem{ 'data-elem_id' => "audio_file-#{elem3.id}" } 
                      -# .elem-image=image_tag("note-blue-32.png")
                      .elem-data{ "data-sound_id" => "sound_id-audio_file-#{elem3.id}", :class => "sound_id-AudioFile"}
                        .duration= Time.at(elem3.length).strftime("%M:%S").sub(/^0/,'')
                        .tracknum= elem3.tracknum
                        .song= elem3.song_name
                        .artist= elem3.artist_name
                        .album= elem3.album_name
                        .url= link_to "#{elem3.song_name} - #{elem3.artist_name}",elem3.url,:remote => true, :class => 'audiofile-link'
                            

                  

app/views/list_nodes/_node3.html.haml
- list_node = nodetree.list_node(node_id)
- children = nodetree.children(node_id)
- playdata_class = list_node_playdata_class(list_node)
- playdata_data = list_node_playdata_data(list_node)
.listnode-elem{ :id => "pl-list_node-#{list_node.id}", :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth} #{playdata_class}", 'data-playdata' => "#{playdata_data}" }

  .listnode-header{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth}" }
    = render :partial => "#{list_node.listable_type.tableize}/controls", :locals => {:list_node => list_node}
    = render :partial => "#{list_node.listable_type.tableize}/elem", :object => nodetree.create_struct(node_id)
  - unless children.empty?
    - if list_node.listable_type == 'Album'
      - artist_count_class = nodetree.n_child_artists(node_id) == 1 ? 'single-artist' : 'multi-artist'
    - else
      - artist_count_class = ''
    .listnode-content{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth} #{artist_count_class}" }
      - children.each do |node_id2|

        - list_node2 = nodetree.list_node(node_id2)
        - children2 = nodetree.children(node_id2)
        - playdata_class2 = list_node_playdata_class(list_node2)
        - playdata_data2 = list_node_playdata_data(list_node2)
        .listnode-elem{ :id => "pl-list_node-#{list_node2.id}", :class => "#{list_node2.listable_type} depth#{list_node2.ancestry_depth} #{playdata_class2}", 'data-playdata' => "#{playdata_data2}" }

          .listnode-header{ :class => "#{list_node2.listable_type} depth#{list_node2.ancestry_depth}" }
            = render :partial => "#{list_node2.listable_type.tableize}/controls", :locals => {:list_node => list_node2}
            = render :partial => "#{list_node2.listable_type.tableize}/elem", :object => nodetree.create_struct(node_id2)
            - unless children2.empty?
              - if list_node2.listable_type == 'Album'
                - artist_count_class = nodetree.n_child_artists(node_id2) == 1 ? 'single-artist' : 'multi-artist'
              - else
                - artist_count_class = ''
              .listnode-content{ :class => "#{list_node2.listable_type} depth#{list_node2.ancestry_depth} #{artist_count_class}" }
                - children2.each do |node_id3|



                  - list_node3 = nodetree.list_node(node_id3)
                  - children3 = nodetree.children(node_id3)
                  - playdata_class3 = list_node_playdata_class(list_node3)
                  - playdata_data3 = list_node_playdata_data(list_node3)
                  .listnode-elem{ :id => "pl-list_node-#{list_node3.id}", :class => "#{list_node3.listable_type} depth#{list_node3.ancestry_depth} #{playdata_class3}", 'data-playdata' => "#{playdata_data3}" }

                    .listnode-header{ :class => "#{list_node3.listable_type} depth#{list_node3.ancestry_depth}" }
                      = render :partial => "#{list_node3.listable_type.tableize}/controls", :locals => {:list_node => list_node3}
                      = render :partial => "#{list_node3.listable_type.tableize}/elem", :object => nodetree.create_struct(node_id3)
                            

                  

app/views/list_nodes/_node_layout.html.haml
- list_node = nodetree.list_node(node_id)
- children = nodetree.children(node_id)
- playdata_class = list_node_playdata_class(list_node)
- playdata_data = list_node_playdata_data(list_node)
.listnode-elem{ :id => "pl-list_node-#{list_node.id}", :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth} #{playdata_class}", 'data-playdata' => "#{playdata_data}" }

  .listnode-header{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth}" }
    = yield :controls
    .listnode-dbg
      = "#{list_node.ancestry_depth}-#{list_node.position}"
    = yield :elem
  - unless children.empty?
    - artist_count_class = nodetree.n_child_artists(node_id) == 1 ? 'single-artist' : ''
    .listnode-content{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth} #{artist_count_class}" }
      - children.each do |nid|
        = render :partial => 'list_nodes/node', :locals => { :nodetree => nodetree, :node_id => nid }

app/views/list_nodes/_nodet.html.haml
- list_node = nodetree.list_node(node_id)
- content_for :controls do
  = render :partial => "#{list_node.listable_type.tableize}/controls", :locals => {:list_node => list_node}

- content_for :elem do
  = render :partial => "#{list_node.listable_type.tableize}/elem", :object => nodetree.create_struct(node_id)

- content_for :child_nodes do
  - children = nodetree.children(node_id)
  - unless children.empty?
    - artist_count_class = nodetree.n_child_artists(node_id) == 1 ? 'single-artist' : ''
    .listnode-content{ :class => "#{list_node.listable_type} depth#{list_node.ancestry_depth} #{artist_count_class}" }
      - children.each do |nid|
        = render :partial => 'list_nodes/node', :locals => { :nodetree => nodetree, :node_id => nid }

app/views/list_nodes/_playlist_playable_items.html.haml
- nodetree.audio_file_list_nodes.each do |list_node|
  - item_class = (playing_playdata =~ /list_node-#{list_node.id}/ ? 'active' : '')
  .item{ :id => "item-list_node-#{list_node.id}", :class => "#{item_class}"}
    = render :partial => "list_nodes/node", :locals => { :nodetree => nodetree, :node_id => list_node.id }

app/views/list_nodes/add_to_playing.js.erb
$('#playing-playlist').find('.ListHead.listnode-content').append("<%= escape_javascript(render(:partial => 'list_nodes/node',:locals => { :nodetree => @nodetree, :node_id => @node_id } )) %>");

$.event.trigger('playlistchanged');
$('#playing-playlist').playlist();

app/views/list_nodes/destroy.js.erb
console.log("list_nodes/destroy.js.erb");
$('#pl-list_node-' + "<%= @node_id %>").remove();

$.event.trigger('playlistchanged');

app/views/list_nodes/edit.html.haml
- model_class = @list_node.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/list_nodes/index.html.haml
= render :partial => 'node', :locals => { :nodetree => @nodetree, :node_id => @node_id }

app/views/list_nodes/new.html.haml
- model_class = @list_node.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"