config/routes.rb
Playit::Application.routes.draw do

  get "one/playlist"

  get "one/search"

  get "one/player"

  get "one/lyric"

  get "one/wiki"

  get "players/mini"
  get "players/simple"

  get "list_nodes/clear"
  get "list_nodes/flatten"
  get "list_nodes/move_to"
  get "list_nodes/add_to_playing"
  post "list_nodes/playlist_playable_items"
  resources :list_nodes

  resources :list_heads

  resources :lyrics

  resources :image_files

  resources :audio_files_tags

  get "audio_files/add_to_playing"
  resources :audio_files do
    member do
      get 'add'
    end
  end

  resources :tags

  resources :genres

  resources :songs

  get "albums/lookup"
  get "albums/add_to_playing"
  get "albums/search"

  resources :albums do
    member do
      get 'image'
      get 'add'
    end
  end

  get "artists/search"
  resources :artists do
    resources :albums do
      get 'add'
    end
  end

  resources :file_dirs

  authenticated :user do
    root :to => 'home#index'
    #root :to => 'one#playlist'
  end
  root :to => "home#index"

  get "home/main"
  get "home/search"
  get "home/dosearch"
  post "home/aside"
  get "home/playing_lyrics"
  get "home/playing_wiki"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/audio_file.rb
class AudioFile < ActiveRecord::Base
  belongs_to :file_dir
  belongs_to :artist
  belongs_to :album
  belongs_to :song
  belongs_to :genre

  attr_accessible :audio_length, :audio_start, :bitrate, :boolean, :file_modified_time, :file_size, :filename, :layer, :length, :mime_type, :mpeg_version, :references, :samplerate, :song, :tracknum, :vbr
  attr_accessible :file_dir, :artist, :album, :song, :genre

  # has_many :audio_files_tags, :dependent => :delete_all
  has_many :audio_files_tags
  has_many :tags, :through => :audio_files_tags

  has_many :list_nodes, :as => :listable

  validates :tracknum, :numericality => true, :allow_nil => true
  validates :bitrate, :numericality => true
  validates :samplerate, :numericality => true
  validates :length, :numericality => true
  validates :layer, :numericality => true, :allow_nil => true
  validates :mpeg_version, :numericality => true, :allow_nil => true

  searchable :auto_index => true, :auto_remove => true do
    integer :id


    text :song_name, :boost => 0.7  do
      song ? song.name : ""
    end
    text :song_name_textp, :stored => true, :boost => 0.1, :as => :name_textp do
      song ? song.name : ""
    end

    text :artist_name, :boost => 0.1  do
      artist ? artist.name : ""
    end
    text :album_name, :boost => 0.3  do
      album ? album.name : ""
    end
    text :lyric_text, :stored => true, :boost => 0.05, :as => :lyric_text_textp  do
      (lyric ? lyric.text : '')
    end

    # text :name, :stored => true, :boost => 7, :as => :name_textp 

    # text :artist_names, :boost => 2, :as => :artist_names_textp  do
    #   (artists.map{ |a| a.name }.uniq.join(' '))
    # end
    # text :album_names, :boost => 2, :as => :album_names_textp  do
    #   (albums.map{ |a| a.name }.uniq.join(' '))
    # end

    integer :artist_id, :references => Artist
    integer :album_id, :references => Album
    # integer :audio_file_ids, :multiple => true, :references => AudioFile
    # integer :lyric_ids, :multiple => true, :references => Lyric
    # integer :genre_ids, :multiple => true, :references => Genre
    integer :song_id, :references => Song
  end

  def create_list_node(list_node,pos=nil)
    pos ||= list_node.child_ids.size + 1
    list_node.children.create(:listable => self, :position => pos)
  end
  alias :create_list_node_all :create_list_node
  def create_list_node_children(list_node,unused = nil)
    list_node
  end



  def lyric
    Lyric.where(:artist_id => self.artist_id, :song_id => self.song_id).first
  end

  def self.limit_to(*els)
    els.flatten.inject(scoped) do |combined_scope,el|
      combined_scope.where( el.class.to_s.foreign_key.to_sym => el.id )
    end
  end


  def artist_name() self.artist.name if self.artist end
  def album_name() self.album.name if self.album end
  def song_name() self.song.name if self.song end
  def genre_name() self.genre.name if self.genre end
  def file_dir_name() self.file_dir.name if self.file_dir end






  def name
    self.song.name
  end

  def filepath
    [self.file_dir.name,self.filename].join('/')
  end


  def fileurl
    self.filepath.sub('/srv/mp3/','')
  end

  def url
    'http://media.kitatdot.net/audio/' + URI.escape(self.fileurl)
    #'/media/' + URI.escape(self.filepath)
  end

  def duration
    Time.at(self.length).strftime("%M:%S").sub(/^0/,'')
  end


  def node_class(node)
    ""
  end



end

app/controllers/audio_files_controller.rb
class AudioFilesController < ApplicationController
  layout Proc.new { |controller| controller.request.xhr? ? false : 'appfixed' }

  def index
    @q = params[:q]
    per_page = 15
    if @q
      @search = Sunspot.search(AudioFile) do |s|
        s.keywords @q
        
        s.paginate :page => params[:page], :per_page => per_page
      end
      @audio_files = @search.results
    else
      @audio_files = AudioFile.page(params[:page]).per(per_page)
    end
  end

  def add
    @id = params[:id]
    list_node = current_user.list_heads.playing.first.list_node
    new_node = AudioFile.find(@id).create_list_node(list_node)
    @node_id = new_node.id
    subtree = ListNode.includes(:listable).ordered.subtree_of(@node_id).all
    @nodetree = NodeTree.new(subtree)

    respond_to do |format|
      format.js
    end
  end

  def add_to_playing
    @id = params[:id]
    list_node = current_user.list_heads.playing.first.list_node
    new_node = AudioFile.find(@id).create_list_node(list_node)
    @node_id = new_node.id
    subtree = ListNode.includes(:listable).ordered.subtree_of(@node_id).all
    @nodetree = NodeTree.new(subtree)

    respond_to do |format|
      format.js
    end
  end



end

app/helpers/audio_files_helper.rb
module AudioFilesHelper

def list_node_playdata_class(node)
  node.listable_type == 'AudioFile' ? "playdata" : nil
end
def list_node_playdata_data(node)
  "list_node-#{node.id}--audio_file-#{node.listable.id}--album-#{node.listable.album_id}" if node.listable_type == 'AudioFile'
end



end

app/views/audio_files/_aside.html.haml
- case context_rec
- when audio_file
  %h3= audio_file.song_name
  %h6= audio_file.artist_name
  = render :partial => audio_file.album, :locals => {:context_rec => context_rec, :lostyle => ''}
  - if audio_file.lyric
    %hr
    %p=audio_file.lyric.html_text.html_safe

- when ::Album
  %tr.elem.playable{ :id => "sr-as-album-#{context_rec}-audio_file-#{audio_file}" }
    %td.elem-image{ :class => 'aside-note' }
      =link_to image_tag("note-blue-16.png"), add_audio_file_path(audio_file.id), :remote => true, :title => "Add '#{audio_file.song_name}' to Playing"
    %td=audio_file.tracknum
    %td=audio_file.song_name

app/views/audio_files/_audio_file.html.haml
= render :partial => 'audio_files/aside', :locals => {:audio_file => audio_file, :context_rec => context_rec, :lostyle => '' }  

app/views/audio_files/_controls.html.haml
.listnode-controls
  .listnode-ctl
    = link_to '<i class="icon-remove"></i>'.html_safe,list_node_path(list_node.id), :method => :delete, :title => "Remove From Playlist", :remote => true, :class => "remove-node"

app/views/audio_files/_elem.html.haml
.elem{ 'data-elem_id' => "audio_file-#{elem.id}" } 
  .elem-image
    = link_to image_tag("note-blue-32.png"), add_audio_file_path(elem.id), :remote => true, :title => "Add '#{elem.song_name}' to Playing"
  .elem-data{ "data-sound_id" => "sound_id-audio_file-#{elem.id}", :class => "sound_id-AudioFile"}
    .duration
      = Time.at(elem.length).strftime("%M:%S").sub(/^0/,'')
    .tracknum
      = elem.tracknum
    .song
      = elem.song_name
    .artist
      = elem.artist_name
    .album
      = elem.album_name
    .url
      = link_to "#{elem.song_name} - #{elem.artist_name}",elem.url,:remote => true, :class => 'audiofile-link'

app/views/audio_files/_form.html.haml
= simple_form_for(@audio_file) do |f|
  = f.error_notification

  .form-inputs
    = f.input :filename
    = f.association :file_dir
    = f.input :file_size
    = f.input :file_modified_time
    = f.association :artist
    = f.association :album
    = f.input :song
    = f.input :references
    = f.association :genre
    = f.input :tracknum
    = f.input :bitrate
    = f.input :samplerate
    = f.input :length
    = f.input :layer
    = f.input :mpeg_version
    = f.input :boolean
    = f.input :audio_start
    = f.input :audio_length
    = f.input :mime_type

  .form-actions
    = f.button :submit

app/views/audio_files/_hit.html.haml
= render :partial => "audio_files/elem", :object => elem

app/views/audio_files/_node.html.haml
.span1
  = "%.3f" % hit.score
.span11.audio_file
  .image
    = image_tag("note-blue-32.png")
  %span.duration
    = Time.at(hit.instance.length).strftime("%M:%S").sub(/^0/,'')
  %span.song
    = hit.instance.song.name
  =" - "
  %span.artist
    = hit.instance.artist.name
  =" - "
  %span.album
    = hit.instance.album.name

app/views/audio_files/add.js.erb
$('#playing-playlist').find('.ListHead.listnode-content .listnode-temp').replaceWith("<%= escape_javascript(render(:partial => 'list_nodes/node',:locals => { :nodetree => @nodetree, :node_id => @node_id } )) %>");

$('#playing-playlist').playlist();
$.event.trigger('playlistchanged');

app/views/audio_files/add_to_playing.js.erb
$('#playing-playlist').find('.ListHead.listnode-content').append("<%= escape_javascript(render(:partial => 'list_nodes/node',:locals => { :nodetree => @nodetree, :node_id => @node_id } )) %>");

$.event.trigger('playlistchanged');

app/views/audio_files/edit.html.haml
%h1 Editing audio_file

= render 'form'

= link_to 'Show', @audio_file
\|
= link_to 'Back', audio_files_path

app/views/audio_files/index.html.haml
- model_class = AudioFile.new.class
.row
  .span9
    %h2=t '.title', :default => model_class.model_name.human.pluralize
.row
  .span9
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Name
          %th Artist
          %th Album
          %th Genre
          %th Length
          %th Actions
      %tbody
        - @audio_files.each do |audio_file|
          %tr
            %td= audio_file.tracknum
            %td= audio_file.song.name
            %td= audio_file.artist.name
            %td= audio_file.album.name
            %td= (audio_file.genre ? audio_file.genre.name : "")
            %td= Time.at(audio_file.length).strftime("%M:%S").sub(/^0/,'')
            %td=link_to "Add to Playing", audio_files_add_to_playing_path(:id => audio_file.id)
              

.row
  .span9
    = paginate @audio_files

app/views/audio_files/new.html.haml
%h1 New audio_file

= render 'form'

= link_to 'Back', audio_files_path

app/views/audio_files/show.html.haml
%p#notice= notice

%p
  %b Filename:
  = @audio_file.filename
%p
  %b File dir:
  = @audio_file.file_dir
%p
  %b File size:
  = @audio_file.file_size
%p
  %b File modified time:
  = @audio_file.file_modified_time
%p
  %b Artist:
  = @audio_file.artist
%p
  %b Album:
  = @audio_file.album
%p
  %b Song:
  = @audio_file.song
%p
  %b References:
  = @audio_file.references
%p
  %b Genre:
  = @audio_file.genre
%p
  %b Tracknum:
  = @audio_file.tracknum
%p
  %b Bitrate:
  = @audio_file.bitrate
%p
  %b Samplerate:
  = @audio_file.samplerate
%p
  %b Length:
  = @audio_file.length
%p
  %b Layer:
  = @audio_file.layer
%p
  %b Mpeg version:
  = @audio_file.mpeg_version
%p
  %b Boolean:
  = @audio_file.boolean
%p
  %b Audio start:
  = @audio_file.audio_start
%p
  %b Audio length:
  = @audio_file.audio_length
%p
  %b Mime type:
  = @audio_file.mime_type

= link_to 'Edit', edit_audio_file_path(@audio_file)
\|
= link_to 'Back', audio_files_path